### ISSUE TITLE
Error when selector don't exists

### ISSUE THREAD

**Issue by paulocoutinhox** [emorozov28/youtube-iframe#1]
Hi,

Can you make a IF to ignore if seletor don't match elements?

Today im getting this error when no video exists:

```
Selector ".js-video-item" not found
```

Thanks.

**Comment by emorozov28** [comment]
Hi,

I fixed the issue. It now ignores missing selectors.

Thanks!

**Comment by paulocoutinhox** [comment]
Hi,

Can you create a new release with it?

Thanks.

**Comment by paulocoutinhox** [comment]
Or it is built in https://github.com/emorozov28/youtube-iframe/tree/main/dist?

**Comment by emorozov28** [comment]
Yes, it is built in - https://github.com/emorozov28/youtube-iframe/tree/main/dist
You can see how it works here - https://github.com/emorozov28/youtube-iframe/tree/main/demo
